force-app/main/default/objects/ToDo__c/ToDo__c.object-meta.xml
<CustomObject>
    <label>ToDo</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ToDos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ToDo__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Today</fullName>
            </value>
            <value>
                <fullName>Tomorrow</fullName>
            </value>
            <value>
                <fullName>Later</fullName>
            </value>
            <value>
                <fullName>Today1</fullName>
                <isActive>false</isActive>
                <label>Today1</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ToDo__c/recordTypes/Later.recordType-meta.xml
<RecordType>
    <fullName>Later</fullName>
    <active>true</active>
    <label>Later</label>
</RecordType>

force-app/main/default/classes/ToDoListControllerTest.cls
@isTest
private class ToDoListControllerTest {
    
    @IsTest
    static void testgetToDos() {
        ToDo__c todo = new ToDo__c(
                Name = 'Test01',
                Category__c = 'Later'
        );
        
        Test.setMock(HttpCalloutMock.class, new TodoHttpCalloutMock());
        Test.startTest();
       	insert todo;
        update todo;
        Test.stopTest();
        
        List<Todo__c> listTodos = ToDoListController.getItems();
        
        System.assertNotEquals(null, listTodos);
        System.assertEquals(1, listTodos.size());
        System.assertEquals('Later', listTodos.get(0).Category__c);
    }
    
    @IsTest
    static void searchTest(){
       ToDo__c todo = new ToDo__c(
                Name = 'test',
                Category__c = 'Later'
        );
        String searchKey = 'test';
        
        Test.setMock(HttpCalloutMock.class, new TodoHttpCalloutMock());
        Test.startTest();
       	insert todo;
        update todo;
        Test.stopTest();
        
        List<Todo__c> listTodos = ToDoListController.searchItems(searchKey);
        
        System.assertNotEquals(null, listTodos);
        System.assertEquals(1, listTodos.size());
        System.assertEquals('test', listTodos.get(0).Name);
        System.assertEquals('Later', listTodos.get(0).Category__c);
    }
   }