force-app/main/default/objects/ToDo__c/ToDo__c.object-meta.xml
<CustomObject>
    <label>ToDo</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ToDos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ToDo__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Today</fullName>
            </value>
            <value>
                <fullName>Tomorrow</fullName>
            </value>
            <value>
                <fullName>Later</fullName>
            </value>
            <value>
                <fullName>Today1</fullName>
                <isActive>false</isActive>
                <label>Today1</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ToDo__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ready to Take</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ToDo__c/recordTypes/Later.recordType-meta.xml
<RecordType>
    <fullName>Later</fullName>
    <active>true</active>
    <label>Later</label>
</RecordType>

force-app/main/default/objects/ToDo__c/recordTypes/Today.recordType-meta.xml
<RecordType>
    <fullName>Today</fullName>
    <active>true</active>
    <label>Today</label>
</RecordType>

force-app/main/default/objects/ToDo__c/recordTypes/Tomorrow.recordType-meta.xml
<RecordType>
    <fullName>Tomorrow</fullName>
    <active>true</active>
    <label>Tomorrow</label>
</RecordType>

force-app/main/default/classes/TodoService.cls
public with sharing class TodoService {
    public static void assignNewTodoToQueue(List<ToDo__c> newTodos) {
        Map<String, Id> queueMap = getQueueMap();
        for (ToDo__c todo : newTodos) {
            if (todo.Status__c == 'Ready to Take' || todo.Status__c == null) {
                todo.Status__c = 'Ready to Take';
                switch on Category.valueOf(todo.Category__c) {
                    when Today {
                        todo.OwnerId = queueMap.get('Today Queue');
                    }
                    when Tomorrow {
                        todo.OwnerId = queueMap.get('Tomorrow Queue');
                    }
                    when else {
                        todo.OwnerId = queueMap.get('Later Queue');
                    }
                }
            }
        }
    }

    public static void reAssignTodoToQueue(List<ToDo__c> todos) {
        Map<String, Id> queueMap = getQueueMap();
        List<Id> queueIds = queueMap.values();
        for (ToDo__c todo : todos) {
            if (queueIds.contains(todo.OwnerId)) {
                switch on Category.valueOf(todo.Category__c) {
                    when Today {
                        todo.OwnerId = queueMap.get('Today Queue');
                    }
                    when Tomorrow {
                        todo.OwnerId = queueMap.get('Tomorrow Queue');
                    }
                    when else {
                        todo.OwnerId = queueMap.get('Later Queue');
                    }
                }
            }
        }
    }

    private static Map<String, Id> getQueueMap() {
        Map<String, Id> queueMap = new Map<String, Id>();
        List<Group> queues = [
            SELECT Id, Name
            FROM Group
            WHERE Type = 'Queue'
        ];
        for (Group queue : queues) {
            queueMap.put(queue.Name, queue.Id);
        }
        return queueMap;
    }

    public static Map<Category, Id> getRocordTypeIdByName() {
        Map<Category, Id> recordTypes = new Map<Category, Id>();
        List<String> categoriesToString = new List<String>();
        Schema.DescribeSObjectResult describeTodoObject = Schema.SObjectType.ToDo__c;
        List<Schema.RecordTypeInfo> recordTypeInfos = describeTodoObject.getRecordTypeInfos();
        List<Category> categories = Category.values();
        for (Category category : categories) {
            categoriesToString.add(category.name());
        }
        for (Schema.RecordTypeInfo recordType : recordTypeInfos) {
            if (categoriesToString.contains(recordType.getName())) {
                recordTypes.put(Category.valueOf(recordType.getName()), recordType.getRecordTypeId());
            }
        }
        return recordTypes;
    }
}