force-app/main/default/objects/ToDo__c/ToDo__c.object-meta.xml
<CustomObject>
    <label>ToDo</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ToDos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ToDo__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Today</fullName>
            </value>
            <value>
                <fullName>Tomorrow</fullName>
            </value>
            <value>
                <fullName>Later</fullName>
            </value>
            <value>
                <fullName>Today1</fullName>
                <isActive>false</isActive>
                <label>Today1</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ToDo__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ready to Take</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ToDo__c/recordTypes/Today.recordType-meta.xml
<RecordType>
    <fullName>Today</fullName>
    <active>true</active>
    <label>Today</label>
</RecordType>

force-app/main/default/objects/ToDo__c/recordTypes/Tomorrow.recordType-meta.xml
<RecordType>
    <fullName>Tomorrow</fullName>
    <active>true</active>
    <label>Tomorrow</label>
</RecordType>

force-app/main/default/classes/ChangeCategoryBatchTest.cls
@IsTest
private class ChangeCategoryBatchTest {
    @IsTest
    static void testChangeCategory() {
        List<ToDo__c> testTodos = new List<ToDo__c>();
        Map<Category, Id> recordTypes = TodoService.getRocordTypeIdByName();
        testTodos.addAll(TestDataFactory.todoCreator(50, recordTypes.get(Category.Today), true, Category.Today));
        for (ToDo__c todo : testTodos) {
            todo.Status__c = 'Completed';
        }
        update testTodos;
        testTodos.addAll(TestDataFactory.todoCreator(50, recordTypes.get(Category.Tomorrow), true, Category.Tomorrow));
        testTodos.addAll(TestDataFactory.todoCreator(50, recordTypes.get(Category.Today), true, Category.Today));
        Test.startTest();
        ChangeCategoryBatch batch = new ChangeCategoryBatch();
        Database.executeBatch(batch);
        Test.stopTest();
        List<ToDo__c> tomorrowTodos = new List<ToDo__c>();
        List<ToDo__c> todayFailedTodos = new List<ToDo__c>();
        List<ToDo__c> todayCompletedTodos = new List<ToDo__c>();
        for (ToDo__c todo : [SELECT Id, Category__c, Status__c FROM ToDo__c]) {
            if (todo.Category__c == 'Tomorrow') {
                tomorrowTodos.add(todo);
            }
            if (todo.Category__c == 'Today' && todo.Status__c == 'Failed') {
                todayFailedTodos.add(todo);
            }
            if (todo.Category__c == 'Today' && todo.Status__c == 'Completed') {
                todayCompletedTodos.add(todo);
            }
        }
        System.assertEquals(0, tomorrowTodos.size());
        System.assertEquals(50, todayFailedTodos.size());
        System.assertEquals(50, todayCompletedTodos.size());
    }
}