force-app/main/default/objects/ToDo__c/ToDo__c.object-meta.xml
<CustomObject>
    <label>ToDo</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ToDos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ToDo__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ready to Take</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ToDo__c/recordTypes/Today.recordType-meta.xml
<RecordType>
    <fullName>Today</fullName>
    <active>true</active>
    <label>Today</label>
</RecordType>

force-app/main/default/classes/CleanOldTodosBatchTest.cls
@IsTest
private class CleanOldTodosBatchTest {
    @IsTest
    static void testDeleteTodo() {
        List<ToDo__c> testTodos = new List<ToDo__c>();
        Map<Category, Id> recordTypes = TodoService.getRocordTypeIdByName();
        testTodos.addAll(TestDataFactory.todoCreator(100, recordTypes.get(Category.Today), true, Category.Today));
        for (ToDo__c todo : testTodos) {
            todo.Status__c = 'Completed';
            Test.setCreatedDate(todo.Id, DateTime.newInstance(2020,12,12));
        }
        update testTodos;
        testTodos.addAll(TestDataFactory.todoCreator(100, recordTypes.get(Category.Today), true, Category.Today));
        Test.startTest();
        CleanOldTodosBatch batch = new CleanOldTodosBatch();
        Database.executeBatch(batch);
        Test.stopTest();
        System.assertEquals(100, [SELECT COUNT() FROM ToDo__c]);
    }
}