force-app/main/default/objects/ToDo__c/ToDo__c.object-meta.xml
<CustomObject>
    <label>ToDo</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ToDos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ToDo__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Today</fullName>
            </value>
            <value>
                <fullName>Tomorrow</fullName>
            </value>
            <value>
                <fullName>Later</fullName>
            </value>
            <value>
                <fullName>Today1</fullName>
                <isActive>false</isActive>
                <label>Today1</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ToDo__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ready to Take</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ResponseWrapperTest.cls
@IsTest
private class ResponseWrapperTest {
    public static ToDo__c todo = new ToDo__c(
        Name = 'Test01',
        ExternalId__c = 'a010900000nVG0NAAW',
        RecordTypeId = '012090000006M9QAAU',
        Status__c = 'Failed'
    );

    @IsTest
    static void testDoingMapping() {
        ResponseWrapper wrapper = new ResponseWrapper();
        wrapper.id = todo.Id;
        wrapper.name = todo.Name;
        wrapper.category = todo.Category__c;
        wrapper.descriprion = todo.Description__c;
        wrapper.priority = todo.Priority__c;
        wrapper.status = todo.Status__c;
        wrapper.externalId = todo.ExternalId__c;
        wrapper.rectypeName = [
            SELECT Name 
            FROM RecordType 
            WHERE Name =: todo.Name
        ].Name;
        System.debug('wrapper: ' + wrapper);

        Test.startTest();
        ResponseWrapper newWrapper = ResponseWrapper.doingMapping(todo);
        Test.stopTest();
        System.debug('new Wrapper ' + newWrapper);

        System.assertEquals(wrapper.id, newWrapper.id);
        System.assertEquals(wrapper.name, newWrapper.name);
        System.assertEquals(wrapper.status, newWrapper.status);
    }

    @IsTest
    static void testdoingMapperToWrappers() {
        ResponseWrapper wrapper = new ResponseWrapper();
        wrapper.id = todo.Id;
        wrapper.name = todo.Name;
        wrapper.status = todo.Status__c;
        wrapper.externalId = todo.ExternalId__c;

        List<ToDo__c> todos = new List<ToDo__c>();
        todos.add(todo);
        System.debug('todos: ' + todos);

        Test.startTest();
        List<ResponseWrapper> wrappers = ResponseWrapper.doingMapperToWrappers(todos);
        Test.stopTest();
        System.debug('wrappers: ' + wrappers);

        for (ResponseWrapper newWrapper : wrappers) {
            System.assertEquals(wrapper.id, newWrapper.id);
            System.assertEquals(wrapper.name, newWrapper.name);
            System.assertEquals(wrapper.status, newWrapper.status);
        }
    }
}