force-app/main/default/objects/ToDo__c/ToDo__c.object-meta.xml
<CustomObject>
    <label>ToDo</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ToDos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ToDo__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Today</fullName>
            </value>
            <value>
                <fullName>Tomorrow</fullName>
            </value>
            <value>
                <fullName>Later</fullName>
            </value>
            <value>
                <fullName>Today1</fullName>
                <isActive>false</isActive>
                <label>Today1</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ToDo__c/recordTypes/Later.recordType-meta.xml
<RecordType>
    <fullName>Later</fullName>
    <active>true</active>
    <label>Later</label>
</RecordType>

force-app/main/default/objects/ToDo__c/recordTypes/Today.recordType-meta.xml
<RecordType>
    <fullName>Today</fullName>
    <active>true</active>
    <label>Today</label>
</RecordType>

force-app/main/default/objects/ToDo__c/recordTypes/Tomorrow.recordType-meta.xml
<RecordType>
    <fullName>Tomorrow</fullName>
    <active>true</active>
    <label>Tomorrow</label>
</RecordType>

force-app/main/default/classes/CreateTodoEmail.cls
global class CreateTodoEmail implements Messaging.InboundEmailHandler {
    private static final String today = 'Today';
    private static final String tomorrow = 'Tomorrow';
    private static final String later = 'Later';

    global Messaging.InboundEmailResult handleInboundEmail(Messaging.inboundEmail email, Messaging.InboundEnvelope envelop) {
        Todo__c todo;
        Id recordTypeId;
        Messaging.InboundEmailResult result = new Messaging.InboundEmailResult();
        String myBody = email.plainTextBody;
        String todoName = email.Subject;
		String todoDescription = email.plainTextBody;
        if (myBody.containsIgnoreCase(today)) {
            recordTypeId = getRocordTypeIdByName(today);
            todo = new Todo__c(Name = todoName, Description__c = todoDescription, Category__c = today, RecordTypeId = recordTypeId);
        } else if (myBody.containsIgnoreCase(tomorrow)) {
            recordTypeId = getRocordTypeIdByName(tomorrow);
            todo = new Todo__c(Name = todoName, Description__c = todoDescription, Category__c = tomorrow, RecordTypeId = recordTypeId);
        } else {
            recordTypeId = getRocordTypeIdByName(later);
            todo = new Todo__c(Name = todoName, Description__c = todoDescription, Category__c = later, RecordTypeId = recordTypeId);
        }
		insert todo;
		return result;
    }

    private static Id getRocordTypeIdByName(String name) {
        Schema.DescribeSObjectResult describeTodoObject = Schema.SObjectType.Todo__c;
        Map<String, Schema.RecordTypeInfo> recordTypeMapByName = describeTodoObject.getRecordTypeInfosByName();
        Schema.RecordTypeInfo recordTypeByName =  recordTypeMapByName.get(name);
        Id recordTypeId = recordTypeByName.getRecordTypeId();
        return recordTypeId;
    }
}