force-app/main/default/objects/ToDo__c/ToDo__c.object-meta.xml
<CustomObject>
    <label>ToDo</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ToDos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ToDo__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ready to Take</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ToDo__c/recordTypes/Today.recordType-meta.xml
<RecordType>
    <fullName>Today</fullName>
    <active>true</active>
    <label>Today</label>
</RecordType>

force-app/main/default/objects/Todo_Setting__mdt/Todo_Setting__mdt.object-meta.xml
<CustomObject>
    <label>Todo Setting</label>
    <pluralLabel>Todo Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Todo_Setting__mdt/fields/Months_For_Storing_Tasks__c.field-meta.xml
<CustomField>
    <fullName>Months_For_Storing_Tasks__c</fullName>
    <description>Number of months of Todos storage</description>
    <label>Months For Storing Tasks</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/CleanOldTodosBatch.cls
public with sharing class CleanOldTodosBatch implements Database.Batchable<sObject> {
    public Database.QueryLocator start(Database.BatchableContext BC) {
        Todo_Setting__mdt month = [
            SELECT Id, Months_For_Storing_Tasks__c, Label
            FROM Todo_Setting__mdt
            LIMIT 1
        ];
        DateTime  today = DateTime.now();
        DateTime  deletionDate = today.addMonths(-Integer.valueOf(month.Months_For_Storing_Tasks__c));
        return Database.getQueryLocator ('SELECT Id, Name FROM ToDo__c ' +
            'WHERE (Status__c = \'Completed\' OR Status__c = \'Failed\') AND CreatedDate <= :deletionDate');
    }

    public void execute(Database.BatchableContext BC, List<ToDo__c> todos) {
        delete todos;
    }

    public void finish(Database.BatchableContext BC) {
    }
}