force-app/main/default/objects/ToDo__c/ToDo__c.object-meta.xml
<CustomObject>
    <label>ToDo</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ToDos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ToDo__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Today</fullName>
            </value>
            <value>
                <fullName>Tomorrow</fullName>
            </value>
            <value>
                <fullName>Later</fullName>
            </value>
            <value>
                <fullName>Today1</fullName>
                <isActive>false</isActive>
                <label>Today1</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ToDo__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ready to Take</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ResponseWrapper.cls
public with sharing class ResponseWrapper {
    public String id {get; set;}
    public String name { get; set; }
    public String descriprion { get; set; }
    public String category { get; set; }
    public String priority { get; set; }
    public String status { get; set; }
    public String externalId { get; set; }
    public String rectypeName { get; set; }
    public String owner { get; set; }
    

    public static ResponseWrapper doingMapping(ToDo__c todo) {
        ResponseWrapper wrapper = new ResponseWrapper();
        wrapper.id = todo.Id;
        wrapper.name = todo.Name;
        wrapper.owner = todo.OwnerId;
        wrapper.category = todo.Category__c;
        wrapper.priority = todo.Priority__c;
        wrapper.status = todo.Status__c;
        wrapper.externalId = todo.ExternalId__c;
        wrapper.rectypeName = [
                                SELECT Name 
                                FROM RecordType 
                                WHERE Id =: todo.RecordTypeId
            ].Name;
        return wrapper;
    }

    public static List<ResponseWrapper> doingMapperToWrappers(List<ToDo__c> todos) {
        List<ResponseWrapper> wrappers = new List<ResponseWrapper>();

        for(ToDo__c todo: todos) {
            ResponseWrapper wrapper = doingMapping(todo);
            wrappers.add(wrapper);
        }
        return wrappers;
    }
}