force-app/main/default/objects/ToDo__c/ToDo__c.object-meta.xml
<CustomObject>
    <label>ToDo</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ToDos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ToDo__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Today</fullName>
            </value>
            <value>
                <fullName>Tomorrow</fullName>
            </value>
            <value>
                <fullName>Later</fullName>
            </value>
            <value>
                <fullName>Today1</fullName>
                <isActive>false</isActive>
                <label>Today1</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ToDo__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ready to Take</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ToDo__c/recordTypes/Today.recordType-meta.xml
<RecordType>
    <fullName>Today</fullName>
    <active>true</active>
    <label>Today</label>
</RecordType>

force-app/main/default/objects/ToDo__c/recordTypes/Tomorrow.recordType-meta.xml
<RecordType>
    <fullName>Tomorrow</fullName>
    <active>true</active>
    <label>Tomorrow</label>
</RecordType>

force-app/main/default/classes/ChangeCategoryBatch.cls
public with sharing class ChangeCategoryBatch implements Database.Batchable<sObject> {
    public Database.QueryLocator start(Database.BatchableContext BC) {
        return Database.getQueryLocator ('SELECT Id, Category__c, RecordTypeId FROM ToDo__c ' +
            'WHERE Status__c != \'Completed\' AND Status__c != \'Failed\'');
    }

    public void execute(Database.BatchableContext BC, List<ToDo__c> todos) {
        Map<Category, Id> recordTypes = TodoService.getRocordTypeIdByName();
        List<ToDo__c> todosToUpdate = new List<ToDo__c>();
        for (ToDo__c todo : todos) {
            if (todo.Category__c == 'Today') {
                todo.Status__c = 'Failed';
                todosToUpdate.add(todo);
            }
            if (todo.Category__c == 'Tomorrow') {
                todo.RecordTypeId = recordTypes.get(Category.Today);
                todo.Category__c = 'Today';
                todosToUpdate.add(todo);
            }
        }
        update todosToUpdate;
    }

    public void finish(Database.BatchableContext BC) {
    }

}