force-app/main/default/objects/Sub_ToDo__c/Sub_ToDo__c.object-meta.xml
<CustomObject>
    <label>Sub ToDo</label>
    <nameField>
        <label>Sub ToDo Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sub ToDos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ToDo__c/ToDo__c.object-meta.xml
<CustomObject>
    <label>ToDo</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ToDos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ToDo__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Today</fullName>
            </value>
            <value>
                <fullName>Tomorrow</fullName>
            </value>
            <value>
                <fullName>Later</fullName>
            </value>
            <value>
                <fullName>Today1</fullName>
                <isActive>false</isActive>
                <label>Today1</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestDataFactory.cls
@IsTest
public class TestDataFactory {
    public static List<ToDo__c> todoCreator(Integer amount, Id recordTypeId, Boolean needInsert, Category category) {
        List<ToDo__c> testTodos = new List<ToDo__c>();
        for (Integer i = 0; i < amount; i++) {
            testTodos.add(new ToDo__c(
                Name = 'Test Todo ' + i,
                RecordTypeId = recordTypeId,
                Category__c = category.name()
            ));
        }
        if (needInsert) {
            insert testTodos;
        }
        return testTodos;
    }

    public static ToDo__c createOneTodo(Id recordTypeId, Boolean needInsert, Category category) {
        ToDo__c testTodo = new ToDo__c(
            Name = 'Test Todo',
            RecordTypeId = recordTypeId,
            Category__c = category.name()
        );
        if (needInsert) {
            insert testTodo;
        }
        return testTodo;
    }

    public static List<Sub_ToDo__c> subTodoCreator(Integer amountForEachTodo, List<ToDo__c> todos, Boolean needInsert) {
        List<Sub_ToDo__c> testSubTodos = new List<Sub_ToDo__c>();
        for (ToDo__c todo : todos) {
            for (Integer i = 0; i < amountForEachTodo; i++) {
                testSubTodos.add(new Sub_ToDo__c(
                    Name = 'Test SubTodo ' + i,
                    ToDo__c = todo.Id
                ));
            }
        }
        if (needInsert) {
            insert testSubTodos;
        }
        return testSubTodos;
    }

    public static List<Sub_ToDo__c> subTodoCreator(Integer amount, ToDo__c todo, Boolean needInsert) {
        List<Sub_ToDo__c> testSubTodos = new List<Sub_ToDo__c>();
        for (Integer i = 0; i < amount; i++) {
            testSubTodos.add(new Sub_ToDo__c(
                Name = 'Test SubTodo ' + i,
                ToDo__c = todo.Id
            ));
        }
        if (needInsert) {
            insert testSubTodos;
        }
        return testSubTodos;
    }
}