force-app/main/default/objects/Sub_ToDo__c/Sub_ToDo__c.object-meta.xml
<CustomObject>
    <label>Sub ToDo</label>
    <nameField>
        <label>Sub ToDo Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sub ToDos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ToDo__c/ToDo__c.object-meta.xml
<CustomObject>
    <label>ToDo</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ToDos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ToDo__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ready to Take</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SubTodoService.cls
public with sharing class SubTodoService {
    public static void markTodoAsCompleted(List<Sub_ToDo__c> subTodos) {
        List<ToDo__c> todoToUpdate = new List<ToDo__c>();
        Set<Id> todoIds = new Set<Id>();
        for (Sub_ToDo__c subTodo : subTodos) {
            todoIds.add(subTodo.ToDo__c);
        }
        for (Sub_ToDo__c subTodo : [
            SELECT Id, Name, ToDo__c, isDone__c, ToDo__r.Status__c
            FROM Sub_ToDo__c
            WHERE ToDo__c IN :todoIds
            AND (isDone__c = false
            OR ToDo__r.Status__c = 'Completed')
        ]) {
            if (todoIds.contains(subTodo.ToDo__c) || subTodo.ToDo__r.Status__c == 'Completed') {
                todoIds.remove(subTodo.ToDo__c);
            }
        }
        for (Id todoId : todoIds) {
            todoToUpdate.add(new ToDo__c(
                Id = todoId,
                Status__c = 'Completed'
            ));
        }
        update todoToUpdate;
    }
}